# Don't change this
theme: jekyll-theme-primer
spec_server: specs.amwa.tv

# AMWA ID
amwa_id: NMOS

# Base name for site (typically lower case version of AMWA ID, or the repo name)
baseurl: /nmos

# Which release or branch appears in header links and on the home page
default_tree: branches/master

# Regex patterns of releases and branches to show
show_releases: 
show_branches: ^master$|^main$|^publish-
