#!/usr/bin/env python3
"""Generate the Zensical/MkDocs source tree for the NMOS spec index.

Inputs (checked into this repo):
  - spec_list.yml   : ordered list of spec slugs
  - themes.yml      : theme groupings (id, name, description, members)

We fetch the published `specs.json` index from specs.amwa.tv. It contains
metadata for every spec, including title, status, default branch, releases,
repository URL and themes. If the fetch fails we fall back to stub entries
so the build still succeeds.

Outputs (written into `docs/`):
  - index.md      : landing page, links to both facets
  - by-theme.md   : specs grouped by theme, sorted within each group
  - by-type.md    : specs grouped by document type (IS / MS / BCP / INFO)
  - tags.md       : Material 'tags' plugin index page
  - specs/<slug>.md : one stub per spec, front-matter-tagged with its
                     type + theme(s) so search/tags act as filters
"""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
import html
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

import yaml

try:
    import requests
except ImportError:  # pragma: no cover - workflow installs it
    requests = None  # type: ignore[assignment]


ROOT = Path(__file__).resolve().parent.parent
# Kept separate from the checked-in `docs/` (which contains hand-authored
# pages like FAQ.md, Introduction.md) so we never overwrite user content.
DOCS = ROOT / "build" / "docs"
SPECS_DIR = DOCS / "specs"

# The published NMOS index is a single JSON array. It contains the correct
# name/status/releases/default_branch data and is generated by the existing
# specs.amwa.tv rendering pipeline.
SPEC_SOURCE = os.environ.get(
    "NMOS_SPEC_SOURCE",
    "https://specs.amwa.tv/nmos/specs.json",
)

# Ordering + display names for the document-type facet. Anything not matched
# here falls into "Other" so nothing silently disappears from the index.
# These entries are maintained in the local NMOS list but the legacy published
# metadata still marks the control feature-set register as hidden. The Zensical
# index is the migration target, so explicitly include it here.
FORCE_ZENSICAL_INCLUDE = {"NMOS-CONTROL-FEATURE-SETS"}


TYPE_ORDER: list[tuple[str, str, str]] = [
    (
        "IS",
        "NMOS Interface Specifications (IS)",
        "APIs defined with RAML, JSON Schema and normative text.",
    ),
    (
        "MS",
        "NMOS Data Model Specifications (MS)",
        "Models for the resources used in NMOS APIs.",
    ),
    ("BCP", "NMOS Best Common Practices (BCP)", "Best practice for use of NMOS APIs."),
    (
        "INFO",
        "NMOS Informative Documents (INFO)",
        "Implementation guides and background information.",
    ),
    (
        "NMOS",
        "NMOS Registers & Feature Sets",
        "Parameter registers and control feature sets.",
    ),
]


@dataclass
class Spec:
    slug: str
    title: str = ""
    repo_name: str = ""
    repo_url: str = ""
    status: str = ""
    url: str = ""
    releases: list[str] = field(default_factory=list)
    default_branch: str = ""
    show_in_index: bool = True
    themes: list[str] = field(default_factory=list)
    intro: dict[str, list[str]] = field(default_factory=dict)

    @property
    def type(self) -> str:
        # Slugs look like IS-04, BCP-003-01, NMOS-PARAMETER-REGISTERS, ...
        head = self.slug.split("-", 1)[0].upper()
        if head in {"IS", "MS", "BCP", "INFO"}:
            return head
        if head == "NMOS":
            return "NMOS"
        return "OTHER"

    @property
    def link(self) -> str:
        return f"specs/{self.slug}.md"


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def fetch_spec_metadata() -> dict[str, dict]:
    """Fetch and index the published specs.json metadata."""
    if requests is None:
        return {}
    url = SPEC_SOURCE.format(slug="nmos", slug_lower="nmos")
    try:
        resp = requests.get(url, timeout=30)
        if resp.status_code != 200:
            print(f"  warn: HTTP {resp.status_code} from {url}", file=sys.stderr)
            return {}
        try:
            data = resp.json()
        except json.JSONDecodeError:
            data = yaml.safe_load(resp.text) or []
        if not isinstance(data, list):
            print(f"  warn: expected a JSON array from {url}", file=sys.stderr)
            return {}
        return {
            str(item.get("amwa_id", "")).upper(): item
            for item in data
            if isinstance(item, dict) and item.get("amwa_id")
        }
    except Exception as exc:  # noqa: BLE001 -- best effort
        print(f"  warn: could not fetch {url}: {exc}", file=sys.stderr)
        return {}


def fetch_increment_repositories() -> dict[str, dict[str, str]]:
    """Return Increment repositories so the NMOS index can host global search."""
    if requests is None:
        return {}
    url = "https://raw.githubusercontent.com/AMWA-TV/in-index/main/index.yml"
    try:
        response = requests.get(url, timeout=15)
        response.raise_for_status()
        data = yaml.safe_load(response.text) or {}
    except Exception as exc:  # noqa: BLE001 -- best-effort supplementary source
        print(f"  warn: could not fetch Increment index: {exc}", file=sys.stderr)
        return {}

    repositories: dict[str, dict[str, str]] = {}
    for document in data.get("documents", []) or []:
        repository = str(document.get("repo", "")).split("/", 1)[-1]
        if repository:
            repositories[repository] = {
                "collection": "AMWA Increments",
                "title": str(document.get("title", repository)),
            }
    return repositories


def fetch_global_manifest(repository: str) -> list[dict]:
    if requests is None:
        return []

    # Versioned repositories publish their current manifest below latest/;
    # fixed-version repositories may publish it at the unversioned root.
    urls = (
        f"https://specs.amwa.tv/new/{repository}/latest/global-search.json",
        f"https://specs.amwa.tv/new/{repository}/global-search.json",
    )
    for url in urls:
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            data = response.json()
        except Exception:
            continue
        documents = data.get("documents", []) if isinstance(data, dict) else []
        return [document for document in documents if isinstance(document, dict)]
    return []


def build_global_search(specs: dict[str, Spec]) -> dict:
    """Merge per-repository manifests into the central static search index."""
    if os.environ.get("AMWA_GLOBAL_SEARCH", "1") == "0":
        return {"version": 1, "documents": []}

    repositories = {
        spec.repo_name: {"collection": "NMOS", "title": spec.title}
        for spec in specs.values()
        if spec.repo_name
    }
    repositories.update(fetch_increment_repositories())

    documents: list[dict] = []
    with ThreadPoolExecutor(max_workers=12) as executor:
        futures = {
            executor.submit(fetch_global_manifest, repository): repository
            for repository in repositories
        }
        for future in as_completed(futures):
            repository = futures[future]
            collection = repositories[repository]["collection"]
            for document in future.result():
                if not document.get("url") or not document.get("text"):
                    continue
                document = dict(document)
                document["repository"] = repository
                document["collection"] = collection
                documents.append(document)

    unique = {document["url"]: document for document in documents}
    return {
        "version": 1,
        "documents": sorted(
            unique.values(),
            key=lambda document: (document.get("title", "").lower(), document["url"]),
        ),
    }


def render_global_search_page() -> str:
    return """# Global AMWA documentation search

Search across the published NMOS specifications, AMWA Increments, and their documentation pages.

<div class="global-search" data-global-search data-index-url="../global-search.json">
  <div class="global-search-controls">
    <input type="search" data-global-search-input aria-label="Search AMWA documentation" placeholder="Search all AMWA documentation…" autofocus>
    <select data-global-search-filter aria-label="Filter by repository">
      <option value="">All repositories</option>
    </select>
  </div>
  <p class="global-search-status" data-global-search-status role="status">Loading the global search index…</p>
  <ol class="global-search-results" data-global-search-results></ol>
</div>
"""


INTRO_HEADINGS = {
    "What does it do?": "what_does_it_do",
    "Why does it matter?": "why_does_it_matter",
    "How does it work?": "how_does_it_work",
}


def readme_intro(text: str) -> dict[str, list[str]]:
    """Extract the standard intro bullet lists from a repository README."""
    if "<!-- INTRO-START -->" in text:
        text = text.split("<!-- INTRO-START -->", 1)[1]
    if "<!-- INTRO-END -->" in text:
        text = text.split("<!-- INTRO-END -->", 1)[0]

    intro: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines():
        heading = re.match(r"^#{2,3}\s+(.+?)\s*$", line)
        if heading:
            current = INTRO_HEADINGS.get(heading.group(1))
            if current:
                intro[current] = []
            continue
        bullet = re.match(r"^\s*-\s+(.+?)\s*$", line)
        if current and bullet:
            intro[current].append(bullet.group(1))

    return {key: values for key, values in intro.items() if values}


def fetch_spec_intro(repository: str, default_branch: str = "") -> dict[str, list[str]]:
    """Fetch intro metadata, falling back to the repository README."""
    if requests is None or not repository:
        return {}

    urls = (
        f"https://specs.amwa.tv/new/{repository}/latest/spec.json",
        f"https://specs.amwa.tv/new/{repository}/spec.json",
    )
    for url in urls:
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            data = response.json()
        except Exception:
            continue
        intro = data.get("intro", {}) if isinstance(data, dict) else {}
        if isinstance(intro, dict):
            result = {
                str(key): [str(item) for item in values]
                for key, values in intro.items()
                if isinstance(values, list) and values
            }
            if result:
                return result

    branches = list(dict.fromkeys(filter(None, (default_branch, "main", "master"))))
    for branch in branches:
        url = f"https://raw.githubusercontent.com/AMWA-TV/{repository}/{branch}/README.md"
        try:
            response = requests.get(url, timeout=10)
            response.raise_for_status()
        except Exception:
            continue
        intro = readme_intro(response.text)
        if intro:
            return intro
    return {}


def populate_spec_intros(specs: dict[str, Spec]) -> None:
    with ThreadPoolExecutor(max_workers=12) as executor:
        futures = {
            executor.submit(fetch_spec_intro, spec.repo_name, spec.default_branch): spec
            for spec in specs.values()
            if spec.repo_name
        }
        for future in as_completed(futures):
            intro = future.result()
            if intro:
                futures[future].intro = intro


def public_spec_url(slug: str, metadata_url: str = "") -> str:
    """Use the beta Zensical/Mike path for links from the NMOS index."""
    url = metadata_url or f"https://specs.amwa.tv/{slug.lower()}"
    # Beta-only routing: remove this conversion and use `url` directly when
    # the Zensical/Mike sites move back from `/new/` to the canonical paths.
    legacy_root = "https://specs.amwa.tv/"
    new_root = "https://specs.amwa.tv/new/"
    if url.startswith(legacy_root) and not url.startswith(new_root):
        return new_root + url[len(legacy_root):].lstrip("/")
    return url


def build_specs(spec_slugs: Iterable[str], themes: list[dict]) -> dict[str, Spec]:
    # Reverse lookup: slug -> [theme id, ...] preserving themes.yml order.
    slug_to_themes: dict[str, list[str]] = {}
    for theme in themes:
        for member in theme.get("members", []) or []:
            slug_to_themes.setdefault(member, []).append(theme["id"])

    metadata = fetch_spec_metadata()
    specs: dict[str, Spec] = {}
    for slug in spec_slugs:
        meta = metadata.get(slug.upper(), {})
        # Keep the local list as the allow-list, but respect the published
        # index's visibility flag for suite/template entries.
        if (
            meta
            and not bool(meta.get("show_in_index", True))
            and slug.upper() not in FORCE_ZENSICAL_INCLUDE
        ):
            continue
        # `name` is the human-friendly title in specs.json; `title` remains
        # supported for compatibility with alternate metadata sources.
        title = meta.get("name") or meta.get("title") or slug
        releases = meta.get("releases") or []
        # specs.json uses either a single string or a list depending on the
        # spec. Normalize both forms before rendering.
        if isinstance(releases, str):
            releases = [releases]
        elif not isinstance(releases, list):
            releases = []
        metadata_themes = meta.get("themes")
        themes_for_spec = (
            [str(theme) for theme in metadata_themes]
            if isinstance(metadata_themes, list)
            else slug_to_themes.get(slug, [])
        )
        specs[slug] = Spec(
            slug=slug,
            title=title,
            repo_name=meta.get("repo_name") or slug.lower(),
            repo_url=meta.get("repo_url") or f"https://github.com/AMWA-TV/{slug.lower()}",
            status=meta.get("status") or "",
            url=public_spec_url(slug, str(meta.get("url") or "")),
            releases=[str(release) for release in releases],
            default_branch=meta.get("default_branch") or "",
            show_in_index=bool(meta.get("show_in_index", True)),
            themes=themes_for_spec,
            intro={
                str(key): [str(item) for item in values]
                for key, values in (meta.get("intro", {}) or {}).items()
                if isinstance(values, list) and values
            },
        )
    return specs


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _sort_key(slug: str) -> tuple:
    """Natural-ish sort so IS-04 comes before IS-10 and BCP-002-01 before -02."""
    parts = re.split(r"[-_]", slug)
    return tuple((0, int(p)) if p.isdigit() else (1, p) for p in parts)


def spec_tooltip_sections(spec: Spec) -> list[tuple[str, list[str]]]:
    labels = (
        ("What does it do?", "what_does_it_do"),
        ("Why does it matter?", "why_does_it_matter"),
        ("How does it work?", "how_does_it_work"),
    )
    sections = []
    for heading, key in labels:
        bullets = []
        for value in spec.intro.get(key, []):
            cleaned = plain_text(str(value).strip())
            if cleaned:
                bullets.append(cleaned)
        if bullets:
            sections.append((heading, bullets))
    return sections


def spec_tooltip_text(spec: Spec, sections: list[tuple[str, list[str]]]) -> str:
    lines = [spec.title]
    for heading, bullets in sections:
        lines.extend(["", heading])
        lines.extend(f"• {bullet}" for bullet in bullets)
    return "\n".join(lines)


def plain_text(value: str) -> str:
    """Remove Markdown syntax before rendering the popup or an HTML attribute."""
    value = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", value)
    value = re.sub(r"``([^`]+)``", r"\1", value)
    return re.sub(r"`([^`]+)`", r"\1", value)


def spec_tooltip_html(spec: Spec, sections: list[tuple[str, list[str]]]) -> str:
    def safe(value: str) -> str:
        # A pipe can otherwise be interpreted as a Markdown table delimiter.
        return html.escape(value).replace("|", "&#124;")

    parts = [f'<span class="in-index-tooltip-title">{safe(spec.title)}</span>']
    for heading, bullets in sections:
        parts.append(
            f'<span class="in-index-tooltip-heading">{safe(heading)}</span>'
        )
        parts.extend(
            f'<span class="in-index-tooltip-item">• {safe(bullet)}</span>'
            for bullet in bullets
        )
    return "".join(parts)


def spec_link(spec: Spec) -> str:
    href = html.escape(spec.url, quote=True)
    label = html.escape(spec.slug)
    sections = spec_tooltip_sections(spec)
    if not sections:
        return f'<a href="{href}">{label}</a>'

    tooltip_text = html.escape(
        plain_text(spec_tooltip_text(spec, sections)).replace("\n", " | "),
        quote=True,
    ).replace("|", "&#124;")
    tooltip_markup = spec_tooltip_html(spec, sections)
    return (
        '<span class="in-index-entry">'
        f'<a href="{href}" aria-label="{tooltip_text}">{label}</a>'
        f'<span class="in-index-tooltip" role="tooltip">{tooltip_markup}</span>'
        "</span>"
    )


def render_spec_stub(spec: Spec, themes_by_id: dict[str, dict]) -> str:
    theme_names = [themes_by_id[t]["name"] for t in spec.themes if t in themes_by_id]
    # Tags let the Material `tags` plugin (and search) filter by type+theme.
    tags = [spec.type] + spec.themes
    front_matter = [
        "---",
        f"title: {spec.title}",
        "tags:",
        *[f"  - {t}" for t in tags],
        "---",
        "",
    ]
    releases_md = release_links(spec) if spec.releases else "_none published_"
    body = [
        f"# {spec.slug} &mdash; {spec.title}",
        "",
        f"- **Document type:** {spec.type}",
        f"- **Status:** {spec.status or '_unknown_'}",
        f"- **Themes:** {', '.join(theme_names) if theme_names else '_none_'}",
        f"- **Canonical URL:** <{spec.url}>",
        f"- **Repository:** <{spec.repo_url}>",
        f"- **Default branch:** `{spec.default_branch or 'unknown'}`",
        f"- **Releases:** {releases_md}",
        "",
    ]
    return "\n".join(front_matter + body)


def render_index() -> str:
    return (
        "# Networked Media Open Specifications\n\n"
        "The tables on the following pages list the current NMOS "
        "specifications, best practices and informative documents. "
        "Use the search box or the tag index to filter by document "
        "type or theme.\n\n"
        "- [By theme](by-theme.md) &mdash; grouped by subject area\n"
        "- [By type](by-type.md) &mdash; grouped by document type\n"
        "- [Tags](tags.md) &mdash; filter by any type or theme\n"
        "- [Global AMWA documentation search](global-search.md) &mdash; search across repositories\n"
    )


def release_links(spec: Spec) -> str:
    """Render the same release links as the legacy NMOS index."""
    if not spec.releases:
        return "&mdash;"
    return "<br>".join(
        f"[{release}]({spec.url.rstrip('/')}/{release})"
        f" [↓]({spec.repo_url}/releases/tag/{release})"
        for release in spec.releases
    )


def release_html(spec: Spec) -> str:
    if not spec.releases:
        return "&mdash;"
    return "<br>".join(
        f'<a href="{html.escape(spec.url.rstrip("/") + "/" + release, quote=True)}">'
        f"{html.escape(release)}</a> "
        f'<a href="{html.escape(spec.repo_url + "/releases/tag/" + release, quote=True)}">'
        "↓</a>"
        for release in spec.releases
    )


def render_spec_table(headers: list[str], rows: list[list[str]]) -> list[str]:
    lines = [
        '<table class="in-index-table">',
        "<thead>",
        "<tr>" + "".join(f"<th>{html.escape(header)}</th>" for header in headers) + "</tr>",
        "</thead>",
        "<tbody>",
    ]
    for row in rows:
        lines.append("<tr>")
        lines.extend(f"<td>{cell}</td>" for cell in row)
        lines.append("</tr>")
    lines.extend(["</tbody>", "</table>"])
    return lines


def branch_html(spec: Spec) -> str:
    return (
        f"<code>{html.escape(spec.default_branch)}</code>"
        if spec.default_branch
        else "&mdash;"
    )


def has_release_column(entries: Iterable[Spec]) -> bool:
    """Return whether a table section contains any versioned specification."""
    return any(spec.releases for spec in entries)


def render_by_theme(specs: dict[str, Spec], themes: list[dict]) -> str:
    lines = ["# Specifications by theme", ""]
    for theme in themes:
        members = sorted(
            (m for m in (theme.get("members") or []) if m in specs),
            key=_sort_key,
        )
        if not members:
            continue
        lines.append(f"## {theme['name']}")
        lines.append("")
        description = theme.get("description")
        if description:
            lines.append(description)
            lines.append("")
        entries = [specs[slug] for slug in members]
        include_releases = has_release_column(entries)
        rows = []
        for spec in entries:
            row = [
                spec_link(spec),
                html.escape(spec.title),
                html.escape(spec.type),
                html.escape(spec.status) if spec.status else "&mdash;",
                branch_html(spec),
            ]
            if include_releases:
                row.append(release_html(spec))
            rows.append(row)
        headers = ["Spec", "Title", "Type", "Status", "Default branch"]
        if include_releases:
            headers.append("Release(s)")
        lines.extend(render_spec_table(headers, rows))
        lines.append("")
    return "\n".join(lines)


def render_by_type(specs: dict[str, Spec]) -> str:
    buckets: dict[str, list[Spec]] = {}
    for spec in specs.values():
        buckets.setdefault(spec.type, []).append(spec)

    lines = ["# Specifications by type", ""]
    seen: set[str] = set()
    for key, heading, blurb in TYPE_ORDER:
        entries = sorted(buckets.get(key, []), key=lambda s: _sort_key(s.slug))
        if not entries:
            continue
        seen.add(key)
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(blurb)
        lines.append("")
        include_releases = has_release_column(entries)
        rows = []
        for spec in entries:
            row = [
                spec_link(spec),
                html.escape(spec.title),
                html.escape(", ".join(spec.themes)) if spec.themes else "&mdash;",
                html.escape(spec.status) if spec.status else "&mdash;",
                branch_html(spec),
            ]
            if include_releases:
                row.append(release_html(spec))
            rows.append(row)
        headers = ["Spec", "Title", "Themes", "Status", "Default branch"]
        if include_releases:
            headers.append("Release(s)")
        lines.extend(render_spec_table(headers, rows))
        lines.append("")

    # Anything unclassified.
    other = sorted(
        (s for k, group in buckets.items() if k not in seen for s in group),
        key=lambda s: _sort_key(s.slug),
    )
    if other:
        lines.append("## Other")
        lines.append("")
        include_releases = has_release_column(other)
        rows = []
        for spec in other:
            row = [
                spec_link(spec),
                html.escape(spec.title),
                html.escape(", ".join(spec.themes)) if spec.themes else "&mdash;",
                html.escape(spec.status) if spec.status else "&mdash;",
                branch_html(spec),
            ]
            if include_releases:
                row.append(release_html(spec))
            rows.append(row)
        headers = ["Spec", "Title", "Themes", "Status", "Default branch"]
        if include_releases:
            headers.append("Release(s)")
        lines.extend(render_spec_table(headers, rows))
        lines.append("")
    return "\n".join(lines)


def tag_anchor(tag: str) -> str:
    return "tag-" + re.sub(r"[^a-z0-9]+", "-", tag.lower()).strip("-")


def render_tags_page(specs: dict[str, Spec]) -> str:
    """Render a tag cloud and explicit tag sections.

    Zensical currently lists the Material `tags` plugin as a compatibility
    backlog item, so relying on its automatic tags index leaves `tags.md`
    empty. Generate the view directly while retaining tags in front matter
    for search and future native tag support.
    """
    grouped: dict[str, list[Spec]] = {}
    for spec in specs.values():
        for tag in [spec.type, *spec.themes]:
            grouped.setdefault(tag, []).append(spec)

    tags = sorted(grouped)
    if not tags:
        return "# Tags\n\n_No tags available._\n"

    largest = max(len(grouped[tag]) for tag in tags)
    cloud = [
        "# Tags",
        "",
        "Filter the specification index by document type or theme. Select a tag to see its matching specifications.",
        "",
        '<div class="tag-cloud" markdown>',
    ]
    for tag in tags:
        # Scale the font modestly according to the number of matching specs.
        size = 0.9 + (0.5 * len(grouped[tag]) / largest)
        label = html.escape(tag)
        cloud.append(
            f'<a href="#{tag_anchor(tag)}" style="font-size: {size:.2f}rem">'
            f"{label} <small>({len(grouped[tag])})</small></a>"
        )
    cloud.extend(["</div>", ""])

    for tag in tags:
        cloud.extend([
            f"## {tag} {{ #{tag_anchor(tag)} }}",
            "",
        ])
        for spec in sorted(grouped[tag], key=lambda item: _sort_key(item.slug)):
            cloud.append(f"- {spec_link(spec)} &mdash; {html.escape(spec.title)}")
        cloud.append("")

    return "\n".join(cloud)


def render_extra_css() -> str:
    return """/* Structured hover/focus popup for README intro bullets. */
.in-index-entry {
  cursor: help;
  display: inline-block;
  position: relative;
  text-decoration: underline dotted;
}

.in-index-tooltip {
  background: var(--md-default-bg-color);
  border: 0.05rem solid var(--md-default-fg-color--light);
  border-radius: 0.3rem;
  box-shadow: var(--md-shadow-z2);
  color: var(--md-default-fg-color);
  display: block;
  font-size: 0.75rem;
  font-weight: 400;
  left: 0;
  line-height: 1.45;
  max-width: min(34rem, calc(100vw - 2rem));
  opacity: 0;
  padding: 0.75rem 1rem;
  pointer-events: none;
  position: absolute;
  text-align: left;
  top: calc(100% + 0.5rem);
  transform: translateY(-0.25rem);
  transition: opacity 120ms ease, transform 120ms ease, visibility 120ms ease;
  visibility: hidden;
  white-space: normal;
  width: max-content;
  overflow-wrap: anywhere;
  z-index: 100;
}

.in-index-entry:hover .in-index-tooltip,
.in-index-entry:focus .in-index-tooltip,
.in-index-entry:focus-within .in-index-tooltip {
  opacity: 1;
  transform: translateY(0);
  visibility: visible;
}

.in-index-tooltip-title,
.in-index-tooltip-heading,
.in-index-tooltip-item {
  display: block;
}

.in-index-tooltip-title {
  font-weight: 700;
  margin-bottom: 0.45rem;
}

.in-index-tooltip-heading {
  font-weight: 700;
  margin-top: 0.45rem;
}

.in-index-tooltip-item {
  font-weight: 400;
}

/* Keep the specification index tables expanded, as on the Increment index. */
.md-typeset table.in-index-table {
  display: table !important;
  max-width: none !important;
  overflow: visible !important;
  table-layout: fixed;
  width: 100% !important;
}

.md-typeset table.in-index-table th,
.md-typeset table.in-index-table td {
  overflow-wrap: anywhere;
}

/* Generated tag-cloud styling for the specification index. */
.tag-cloud {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.5rem;
  margin: 1rem 0 2rem;
}

.tag-cloud a {
  display: inline-block;
  padding: 0.25rem 0.7rem;
  border: 1px solid var(--md-default-fg-color--lightest);
  border-radius: 999px;
  text-decoration: none;
}

.tag-cloud a:hover {
  border-color: var(--md-primary-fg-color);
}

.tag-cloud small {
  opacity: 0.7;
}
"""


def main() -> int:
    spec_slugs = load_yaml(ROOT / "spec_list.yml") or []
    themes = load_yaml(ROOT / "themes.yml") or []
    themes_by_id = {t["id"]: t for t in themes}

    print(f"Loaded {len(spec_slugs)} specs across {len(themes)} themes.")

    specs = build_specs(spec_slugs, themes)
    populate_spec_intros(specs)

    DOCS.mkdir(parents=True, exist_ok=True)
    SPECS_DIR.mkdir(parents=True, exist_ok=True)

    (DOCS / "index.md").write_text(render_index(), encoding="utf-8")
    (DOCS / "by-theme.md").write_text(render_by_theme(specs, themes), encoding="utf-8")
    (DOCS / "by-type.md").write_text(render_by_type(specs), encoding="utf-8")
    (DOCS / "tags.md").write_text(render_tags_page(specs), encoding="utf-8")
    (DOCS / "global-search.md").write_text(render_global_search_page(), encoding="utf-8")
    global_search = build_global_search(specs)
    (DOCS / "global-search.json").write_text(
        json.dumps(global_search, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    styles_dir = DOCS / "stylesheets"
    styles_dir.mkdir(parents=True, exist_ok=True)
    (styles_dir / "extra.css").write_text(render_extra_css(), encoding="utf-8")
    shutil.copy2(
        ROOT / ".docs" / "global-search" / "global-search.css",
        styles_dir / "global-search.css",
    )
    scripts_dir = DOCS / "javascripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(
        ROOT / ".docs" / "global-search" / "global-search.js",
        scripts_dir / "global-search.js",
    )

    for spec in specs.values():
        (SPECS_DIR / f"{spec.slug}.md").write_text(
            render_spec_stub(spec, themes_by_id), encoding="utf-8"
        )

    print(f"Wrote {len(specs)} spec pages + 5 index pages to {DOCS}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
