#!/bin/bash
for INFILE in *.raml
do
  echo "Found RAML file" $INFILE
  OUTFILE=${INFILE::-5}
  raml2html $INFILE > $OUTFILE.html
  echo "Generated" $OUTFILE.html
  #if [ -e /usr/bin/ramltomd ]; then
  #  ramltomd -i $INFILE > $OUTFILE.md
  #  echo "Generated" $OUTFILE.md
  #fi
done
echo ""
echo "Linting..."
jsonlint -v examples/*.json
echo ""
jsonlint -v schemas/*.json

