name: Render
on:
  push:
    branches:
        - 'v[0-9]+.[0-9]+-dev'
        - 'v[0-9]+.[0-9]+.x'
        - 'publish-*'
    tags:
        - 'v[0-9]+.[0-9]+'
        - 'v[0-9]+.[0-9]+.[0-9]+'
  release:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - name: Install Bundler
        run: gem install bundler
      - name: Setup 
        run: make -C render distclean build-tools
      - name: Build site
        run: make -C render build
      - name: Upload site
        run: make -C render upload
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }} 
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
